export interface Movie{
    title : Array<string>;
}


export const MovieTitles : Array<Movie> =  [
    { title: ["Psycho"] },
    { title: ["Nightmare", "on", "Elm", "Street"] },
    { title: ["Halloween"] },
    { title: ["Silence", "of", "the", "Lambs"] },
    { title: ["Hereditary"] },
    { title: ["Rosemary's", "Baby"] },
    { title: ["The", "Shining"] },
    { title: ["Carrie"] },
    { title: ["Jaws"] },
    { title: ["The", "Sixth", "Sense"] },
    { title: ["The", "Silence", "of", "the", "Lambs"] },
    { title: ["Cannibal", "Holocaust"] },
    { title: ["The", "Conjuring"] },
    { title: ["A", "Nightmare", "on", "Elm", "Street"] },
    { title: ["The", "Hills", "Have", "Eyes"] },
    { title: ["Friday", "the", "13th"] },
    { title: ["The", "Exorcism", "of", "Emily", "Rose"] },
    { title: ["Blair", "Witch", "Project"] },
    { title: ["The", "Cabin", "in", "the", "Woods"] },
    { title: ["Don't", "Breathe"] },
    { title: ["Insidious"] },
    { title: ["The", "Human", "Centipede"] },
    { title: ["The", "Wicker", "Man"] },
    { title: ["The", "Mummy"] },
    { title: ["The", "Others"] },
    { title: ["The", "Thing"] },
    { title: ["American", "Psycho"] },
    { title: ["The", "Fly"] },
    { title: ["Annabelle"] },
    { title: ["The", "Nun"] },
    { title: ["The", "Grudge"] },
    { title: ["The", "Ring"] },
    { title: ["Paranormal", "Activity"] },
    { title: ["Get", "Out"] },
    { title: ["A", "Quiet", "Place"] },
    { title: ["The", "Babadook"] },
    { title: ["It", "Follows"] },
    { title: ["The", "Descent"] },
    { title: ["Sinister"] },
    { title: ["Midsommar"] },
    { title: ["Us"] },
    { title: ["The", "Visit"] },
    { title: ["The", "Orphanage"] },
    { title: ["Let", "the", "Right", "One", "In"] },
    { title: ["The", "Strangers"] },
    { title: ["Evil", "Dead"] },
    { title: ["The", "Evil", "Within"] },
    { title: ["Martyrs"] },
    { title: ["The", "Crazies"] },
    { title: ["The", "Autopsy", "of", "Jane", "Doe"] },
    { title: ["Crimson", "Peak"] },
    { title: ["Donnie", "Darko"] },
    { title: ["The", "Silent", "House"] },
    { title: ["The", "Purge"] },
    { title: ["The", "Babadook"] },
    { title: ["Orphan"] },
    { title: ["The", "Lighthouse"] },
    { title: ["The", "Witch"] },
    { title: ["Creep"] },
    { title: ["The", "Neon", "Demon"] },
    { title: ["Mother!"] },
    { title: ["The", "Killing", "of", "a", "Sacred", "Deer"] },
    { title: ["The", "Ritual"] },
    { title: ["As", "Above,", "So", "Below"] },
    { title: ["The", "Cloverfield", "Paradox"] },
    { title: ["The", "Bye", "Bye", "Man"] },
    { title: ["The", "Shallows"] },
    { title: ["Lights", "Out"] },
    { title: ["The", "Invisible", "Man"] },
    { title: ["The", "Wailing"] },
    { title: ["The", "Platform"] },
    { title: ["The", "Mist"] },
    { title: ["The", "Host"] },
    { title: ["The", "Silent", "Hill"] },
    { title: ["The", "Ruins"] },
    { title: ["The", "Happening"] },
    { title: ["The", "Cell"] },
    { title: ["The", "Langoliers"] },
    { title: ["Cube"] },
    { title: ["The", "Game"] },
    { title: ["Triangle"] },
    { title: ["The", "Cabin", "in", "the", "Woods"] },
    { title: ["The", "Village"] },
    { title: ["The", "Platform"] },
    { title: ["The", "Lobster"] },
    { title: ["The", "Hunt"] },
    { title: ["Get", "Out"] },
    { title: ["A", "Quiet", "Place"] },
    { title: ["The", "Silent", "House"] },
    { title: ['The', 'Conjuring', '3:','The', 'Devil', 'Made', 'Me', 'Do', 'It'] },
  { title: ['A', 'Quiet', 'Place', 'Part', 'II'] },
  { title: ['Candyman'] },
  { title: ['Malignant'] },
  { title: ['The', 'Forever', 'Purge'] },
  { title: ['The', 'Nighthouse'] },
  { title: ['Antlers'] },
  { title: ['The', 'Night', 'House'] },
  { title: ['Don’t', 'Breathe', '2'] },
  { title: ['Escape', 'Room:', 'Tournament', 'of', 'Champions'] },
  { title: ['Last', 'Night', 'in', 'Soho'] },
  { title: ['The', 'Green', 'Knight'] },
  { title: ['Halloween', 'Kills'] },
  { title: ['The', 'Card', 'Counter'] },
  { title: ['The', 'Many', 'Saints', 'of', 'Newark'] },
  { title: ['Venom:', 'Let', 'There', 'Be', 'Carnage'] },
  { title: ['Old'] },
  { title: ['The', 'Eternals'] },
  { title: ['The', 'Suicide', 'Squad'] },
  { title: ['Army', 'of', 'the', 'Dead'] },
    
  ];

  export const  animeMovies : Array<Movie> = [
    { title: ['Spirited', 'Away'] },
    { title: ['Your', 'Name'] },
    { title: ['Akira'] },
    { title: ['Princess', 'Mononoke'] },
    { title: ['Grave', 'of', 'the', 'Fireflies'] },
    { title: ['My', 'Neighbor', 'Totoro'] },
    { title: ['Ghost', 'in', 'the', 'Shell'] },
    { title: ['Neon', 'Genesis', 'Evangelion:', 'The', 'End', 'of', 'Evangelion'] },
    { title: ['Perfect', 'Blue'] },
    { title: ['Paprika'] },
    { title: ['Cowboy', 'Bebop:', 'The', 'Movie'] },
    { title: ['Demon', 'Slayer:', 'Mugen', 'Train'] },
    { title: ['The', 'Red', 'Turtle'] },
    { title: ['A', 'Silent', 'Voice'] },
    { title: ['Howl’s', 'Moving', 'Castle'] },
    { title: ['Attack', 'on', 'Titan:', 'Crimson', 'Bow', 'and', 'Arrow'] },
    { title: ['Weathering', 'with', 'You'] },
    { title: ['Akira'] },
    { title: ['The', 'Girl', 'Who', 'Leapt', 'Through', 'Time'] },
    { title: ['Nausicaä', 'of', 'the', 'Valley', 'of', 'the', 'Wind'] },
    { title: ['Sword', 'of', 'the', 'Stranger'] },
    { title: ['Steamboy'] },
    { title: ['The', 'Boy', 'and', 'the', 'Beast'] },
    { title: ['Wolf', 'Children'] },
    { title: ['Ponyo'] },
    { title: ['The', 'Wind', 'Rises'] },
    { title: ['Tokyo', 'Godfathers'] },
    { title: ['A', 'Whisker', 'Away'] },
    { title: ['The', 'Promised', 'Neverland:', 'Confinement'] },
    { title: ['Kiki’s', 'Delivery', 'Service'] },
    { title: ['The', 'Castle', 'of', 'Cagliostro'] },
    { title: ['Summer', 'Wars'] },
    { title: ['Lu', 'Over', 'the', 'Wall'] },
    { title: ['Maquia:', 'When', 'the', 'Promised', 'Flower', 'Blooms'] },
    { title: ['Red', 'Line'] },
    { title: ['Millennium', 'Actress'] },
    { title: ['Tokyo', 'Story'] },
    { title: ['Children', 'of', 'the', 'Sea'] },
    { title: ['The', 'Garden', 'of', 'Words'] },
    { title: ['Porco', 'Rosso'] },
    { title: ['Memories'] },
    { title: ['Mind', 'Game'] },
    { title: ['Colorful'] },
    { title: ['Jin-Roh:', 'The', 'Wolf', 'Brigade'] },
    { title: ['K-On!:', 'The', 'Movie'] },
    { title: ['The', 'Night', 'Is', 'Short,', 'Walk', 'on', 'Girl'] },
    { title: ['The', 'Case', 'of', 'Hana', '&', 'Alice'] },
    { title: ['Belladonna', 'of', 'Sadness'] },
    { title: ['Wings', 'of', 'Honneamise'] },
  ];

 export const Titles : Array<Movie> =  [

    { title: ["The", "Cloverfield", "Paradox"] },

    {title : ["American", "Psycho"]},

    { title: ["The", "Invisible", "Man"] },
    { title: ['The', 'Conjuring', '3:','The', 'Devil', 'Made', 'Me', 'Do', 'It'] },
  { title: ['Candyman'] },
  { title: ['Malignant'] },
  { title: ['The', 'Forever', 'Purge'] },
  { title: ['The', 'Nighthouse'] },
  { title: ['Antlers'] },
  { title: ['The', 'Night', 'House'] },
  { title: ['Don’t', 'Breathe', '2'] },
  { title: ['Last', 'Night', 'in', 'Soho'] },
  { title: ['The', 'Green', 'Knight'] },
  { title: ['Halloween', 'Kills'] },
  { title: ['The', 'Card', 'Counter'] },
  { title: ['Venom:', 'Let', 'There', 'Be', 'Carnage'] },
  { title: ['The', 'Suicide', 'Squad'] },
  { title: ['Army', 'of', 'the', 'Dead'] },

  { title: ['Demon', 'Slayer:', 'Mugen', 'Train'] },
  { title: ['The', 'Red', 'Turtle'] },
  { title: ['A', 'Silent', 'Voice'] },
  { title: ['Howl’s', 'Moving', 'Castle'] },
  { title: ['Attack', 'on', 'Titan:', 'Crimson', 'Bow', 'and', 'Arrow'] },
  { title: ['Weathering', 'with', 'You'] },
  { title: ['Akira'] },
  { title: ['The', 'Girl', 'Who', 'Leapt', 'Through', 'Time'] },
  { title: ['Nausicaä', 'of', 'the', 'Valley', 'of', 'the', 'Wind'] },
  { title: ['Sword', 'of', 'the', 'Stranger'] },
  { title: ['Steamboy'] },
  { title: ['The', 'Boy', 'and', 'the', 'Beast'] },
  { title: ['Wolf', 'Children'] },
  { title: ['Ponyo'] },
  { title: ['The', 'Wind', 'Rises'] },
  { title: ['Tokyo', 'Godfathers'] },
  ]

  export const actionMovies : Array<Movie> = [
    { title: ['The', 'Matrix'] },
    { title: ['Die', 'Hard'] },
    { title: ['Mad', 'Max:', 'Fury', 'Road'] },
    { title: ['John', 'Wick'] },
    { title: ['Mission:', 'Impossible'] },
    { title: ['The', 'Dark', 'Knight'] },
    { title: ['Terminator', '2:', 'Judgment', 'Day'] },
    { title: ['Gladiator'] },
    { title: ['Inception'] },
    { title: ['Black', 'Panther'] },
    { title: ['Kill', 'Bill:', 'Vol.', '1'] },
    { title: ['The', 'Equalizer'] },
    { title: ['The', 'Bourne', 'Identity'] },
    { title: ['Speed'] },
    { title: ['Taken'] },
    { title: ['Avengers:', 'Endgame'] },
    { title: ['Braveheart'] },
    { title: ['Rambo:', 'First', 'Blood'] },
    { title: ['Jurassic', 'Park'] },
    { title: ['Lethal', 'Weapon'] },
    { title: ['Pulp', 'Fiction'] },
    { title: ['The', 'Rock'] },
    { title: ['Die', 'Hard', 'With', 'a', 'Vengeance'] },
    { title: ['Atomic', 'Blonde'] },
    { title: ['The', 'Raid'] },
    { title: ['The', 'Transporter'] },
    { title: ['Django', 'Unchained'] },
    { title: ['Heat'] },
    { title: ['The', 'Expendables'] },
    { title: ['Spider-Man:', 'Into', 'the', 'Spider-Verse'] },
  ];

  export const scienceFictionMovies : Array<Movie> = [
    { title: ['Blade', 'Runner'] },
    { title: ['Interstellar'] },
    { title: ['The', 'Fifth', 'Element'] },
    { title: ['Ender\'s', 'Game'] },
    { title: ['The', 'Martian'] },
    { title: ['Star', 'Wars:', 'A', 'New', 'Hope'] },
    { title: ['The', 'Time', 'Machine'] },
    { title: ['Arrival'] },
    { title: ['The', 'Hitchhiker\'s', 'Guide', 'to', 'the', 'Galaxy'] },
    { title: ['The', 'Terminator'] },
    { title: ['The', 'Day', 'the', 'Earth', 'Stood', 'Still'] },
    { title: ['War', 'of', 'the', 'Worlds'] },
    { title: ['Invasion', 'of', 'the', 'Body', 'Snatchers'] },
    { title: ['The', 'Truman', 'Show'] },
    { title: ['District', '9'] },
    { title: ['Avatar'] },
    { title: ['The', 'Fly'] },
    { title: ['The', 'Matrix'] },
    { title: ['A.I.', 'Artificial', 'Intelligence'] },
    { title: ['Ex', 'Machina'] },
    { title: ['Star', 'Trek:', 'The', 'Motion', 'Picture'] },
    { title: ['Snowpiercer'] },
    { title: ['Children', 'of', 'Men'] },
    { title: ['The', 'Incredible', 'Hulk'] },
    { title: ['Looper'] },
    { title: ['The', 'Island'] },
    { title: ['Edge', 'of', 'Tomorrow'] },
    { title: ['Pacific', 'Rim'] },
    { title: ['The', 'Andromeda', 'Strain'] },
    { title: ['Donnie', 'Darko'] },
  ];

  export const mysteryMovies : Array<Movie> = [
    { title: ['Sherlock', 'Holmes'] },
    { title: ['Gone', 'Girl'] },
    { title: ['The', 'Usual', 'Suspects'] },
    { title: ['Se7en'] },
    { title: ['Memento'] },
    { title: ['The', 'Girl', 'with', 'the', 'Dragon', 'Tattoo'] },
    { title: ['Chinatown'] },
    { title: ['Prisoners'] },
    { title: ['Shutter', 'Island'] },
    { title: ['The', 'Silence', 'of', 'the', 'Lambs'] },
    { title: ['Zodiac'] },
    { title: ['Knives', 'Out'] },
    { title: ['The', 'Da', 'Vinci', 'Code'] },
    { title: ['The', 'Departed'] },
    { title: ['Insomnia'] },
    { title: ['Murder', 'on', 'the', 'Orient', 'Express'] },
    { title: ['The', 'Bone', 'Collector'] },
    { title: ['Wind', 'River'] },
    { title: ['Identity'] },
    { title: ['The', 'Prestige'] },
    { title: ['The', 'Others'] },
    { title: ['Gosford', 'Park'] },
    { title: ['Mystic', 'River'] },
    { title: ['The', 'Hound', 'of', 'the', 'Baskervilles'] },
    { title: ['Eyes', 'Wide', 'Shut'] },
    { title: ['Secret', 'Window'] },
    { title: ['And', 'Then', 'There', 'Were', 'None'] },
    { title: ['The', 'Ghost', 'Writer'] },
    { title: ['Dark', 'City'] },
    { title: ['The', 'Maltese', 'Falcon'] },
  ];

 export const adventureMovies : Array<Movie> = [
    { title: ['Indiana', 'Jones:', 'Raiders', 'of', 'the', 'Lost', 'Ark'] },
    { title: ['The', 'Lord', 'of', 'the', 'Rings:', 'The', 'Fellowship', 'of', 'the', 'Ring'] },
    { title: ['Pirates', 'of', 'the', 'Caribbean:', 'The', 'Curse', 'of', 'the', 'Black', 'Pearl'] },
    { title: ['Jurassic', 'Park'] },
    { title: ['National', 'Treasure'] },
    { title: ['The', 'Revenant'] },
    { title: ['Avatar'] },
    { title: ['Jumanji:', 'Welcome', 'to', 'the', 'Jungle'] },
    { title: ['The', 'Goonies'] },
    { title: ['The', 'Princess', 'Bride'] },
    { title: ['The', 'Mummy'] },
    { title: ['Cast', 'Away'] },
    { title: ['Life', 'of', 'Pi'] },
    { title: ['Indiana', 'Jones:', 'The', 'Last', 'Crusade'] },
    { title: ['Mad', 'Max:', 'Fury', 'Road'] },
    { title: ['The', 'Hobbit:', 'An', 'Unexpected', 'Journey'] },
    { title: ['The', 'Swiss', 'Family', 'Robinson'] },
    { title: ['Robin', 'Hood:', 'Prince', 'of', 'Thieves'] },
    { title: ['King', 'Kong'] },
    { title: ['The', 'Adventures', 'of', 'Tintin'] },
    { title: ['The', 'Jungle', 'Book'] },
    { title: ['The', 'Lost', 'City', 'of', 'Z'] },
    { title: ['The', 'Secret', 'Life', 'of', 'Walter', 'Mitty'] },
    { title: ['The', 'Call', 'of', 'the', 'Wild'] },
    { title: ['Up'] },
    { title: ['The', 'Great', 'Escape'] },
    { title: ['The', 'Bridge', 'on', 'the', 'River', 'Kwai'] },
    { title: ['The', 'African', 'Queen'] },
    { title: ['The', 'Treasure', 'of', 'the', 'Sierra', 'Madre'] },
  ];

 export const comedyMovies : Array<Movie> = [
    { title: ['Dumb', 'and', 'Dumber'] },
    { title: ['The', 'Hangover'] },
    { title: ['Superbad'] },
    { title: ['Anchorman:', 'The', 'Legend', 'of', 'Ron', 'Burgundy'] },
    { title: ['Bridesmaids'] },
    { title: ['Ferris', 'Bueller’s', 'Day', 'Off'] },
    { title: ['The', 'Grand', 'Budapest', 'Hotel'] },
    { title: ['Ghostbusters'] },
    { title: ['Airplane!'] },
    { title: ['The', 'Princess', 'Diaries'] },
    { title: ['Napoleon', 'Dynamite'] },
    { title: ['Groundhog', 'Day'] },
    { title: ['Freaky', 'Friday'] },
    { title: ['The', '40-Year-Old', 'Virgin'] },
    { title: ['Ted'] },
    { title: ['Step', 'Brothers'] },
    { title: ['Dodgeball:', 'A', 'True', 'Underdog', 'Story'] },
    { title: ['The', 'Devil', 'Wears', 'Prada'] },
    { title: ['This', 'Is', 'the', 'End'] },
    { title: ['Pitch', 'Perfect'] },
    { title: ['Zoolander'] },
    { title: ['The', 'Lego', 'Movie'] },
    { title: ['Ghost', 'Town'] },
    { title: ['Mean', 'Girls'] },
    { title: ['Hot', 'Fuzz'] },
    { title: ['The', 'Big', 'Lebowski'] },
    { title: ['My', 'Big', 'Fat', 'Greek', 'Wedding'] },
    { title: ['Shrek'] },
    { title: ['The', 'Princess', 'Bride'] },
    { title: ['Clueless'] },
  ];

  //Mix all 20 of each genre into one array


  const allMovies : Array<Movie> = [

  ];

  for(let i = 0; i < 20; i++){
    allMovies.push(actionMovies[i]);
    allMovies.push(adventureMovies[i]);
    allMovies.push(comedyMovies[i]);
    allMovies.push(mysteryMovies[i]);
    allMovies.push(scienceFictionMovies[i]);
  }

  export const allTitles : Array<Movie> = allMovies;